export const GET_TWEET_FEED_REQUEST = "GET_TWEET_FEED_REQUEST"
export const GET_TWEET_FEED_SUCCESS = "GET_TWEET_FEED_SUCCESS"


export const CREATE_TWEET_REQUEST = "CREATE_TWEET_REQUEST"
export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS"
export const CREATE_TWEET_FAILED = "CREATE_TWEET_FAILED"